// Generated by CoffeeScript 2.0.3
(function() {
  "use strict";
  var defaults, parser, processors;

  defaults = require('./defaults');

  parser = require('./parser');

  processors = require('./processors');

  exports.defaults = defaults.defaults;

  exports.processors = processors;

  exports.ValidationError = class ValidationError extends Error {
    constructor(message) {
      super(message);
      this.message = message;
    }

  };

  exports.Parser = parser.Parser;

  exports.parseString = parser.parseString;

}).call(this);
